// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Gov.News.Api
{
    using Gov.News.Api.Models;
    using System.Threading.Tasks;
  

    /// <summary>
    /// Set the currentAPIVersion.  Used by all calls.
    /// </summary>
    public static partial class ClientExtensions
    {
        public const string currentAPIVersion = "1.0";
    }
}
